# Generated by Django 5.0.2 on 2024-04-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_number_of_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
