# Generated by Django 5.0.2 on 2024-05-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customerotp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOtp',
            new_name='UserOtp',
        ),
    ]
