# Generated by Django 5.0.2 on 2024-05-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_customerotp_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='email_id',
            new_name='email',
        ),
    ]
