# Generated by Django 5.0.2 on 2024-06-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rename_email_id_userotp_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crmuserfamilyinformation',
            table='User_FamilyInformation',
        ),
        migrations.AlterModelTable(
            name='userotp',
            table='userOtp',
        ),
    ]
