# Generated by Django 5.0.2 on 2024-06-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_crmuserfamilyinformation_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='crmuserfamilyinformation',
            table='user_family_information',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userotp',
            table='user_otp',
        ),
    ]
