# Generated by Django 5.0.2 on 2024-06-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crmuserexperience',
            table='user_experience_information',
        ),
    ]
