# Generated by Django 5.0.2 on 2024-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='organization',
            new_name='company',
        ),
        migrations.AddField(
            model_name='lead',
            name='organization_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
