# Generated by Django 5.0.2 on 2024-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email_opted_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
