# Generated by Django 5.0.2 on 2024-06-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_email_opted_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_owner',
            new_name='record_owner',
        ),
    ]
