# Generated by Django 5.0.2 on 2024-04-25 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_photos/')),
                ('prefix', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('email_opted_out', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=16)),
                ('home_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('mobile_phone', models.CharField(max_length=16)),
                ('other_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('assistant_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('assistant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('mailing_address', models.TextField()),
                ('mailing_city', models.CharField(max_length=50)),
                ('mailing_state', models.CharField(max_length=50)),
                ('mailing_postal_code', models.CharField(max_length=15)),
                ('mailing_country', models.CharField(max_length=100)),
                ('other_address', models.TextField(blank=True, null=True)),
                ('other_city', models.CharField(blank=True, max_length=50, null=True)),
                ('other_state', models.CharField(blank=True, max_length=50, null=True)),
                ('other_postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('other_country', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permission', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_list', models.CharField(blank=True, max_length=150, null=True)),
                ('permissions', models.CharField(blank=True, max_length=150, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
                ('record_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
