# Generated by Django 5.0.2 on 2024-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_company_alter_contact_mailing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organization_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
