# Generated by Django 5.0.2 on 2024-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organization_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
