# Generated by Django 5.0.2 on 2024-04-25 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('name', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=25)),
                ('fax', models.CharField(max_length=25)),
                ('website', models.CharField(max_length=150)),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('email_domains', models.CharField(max_length=250)),
                ('billing_address', models.TextField()),
                ('billing_city', models.CharField(max_length=150)),
                ('billing_state', models.CharField(max_length=150)),
                ('billing_postal_code', models.CharField(max_length=25)),
                ('billing_country', models.CharField(max_length=150)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=150, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=150, null=True)),
                ('shipping_postal_code', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=150, null=True)),
                ('date_to_remember', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag_list', models.CharField(blank=True, max_length=250, null=True)),
                ('permission', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('record_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('company_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recently_viewed', to='organizations.company')),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
