# Generated by Django 5.0.2 on 2024-06-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_content_message_receiver_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
