# Generated by Django 5.0.2 on 2024-06-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
