# Generated by Django 5.0.2 on 2024-06-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_conversation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
    ]
