# Generated by Django 5.0.2 on 2024-06-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_message_conversation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='Conversation',
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
