# Generated by Django 5.0.2 on 2024-04-25 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='deal_images/')),
                ('prefix', models.CharField(blank=True, max_length=25, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('email_opted_out', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('industry', models.CharField(blank=True, max_length=150, null=True)),
                ('number_of_employees', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, default='Email', max_length=150, null=True)),
                ('probability_of_winning', models.CharField(blank=True, default='Email', max_length=150, null=True)),
                ('forecast_close_date', models.CharField(blank=True, max_length=150, null=True)),
                ('actual_close_date', models.CharField(blank=True, max_length=150, null=True)),
                ('deal_value', models.CharField(blank=True, max_length=100, null=True)),
                ('bid_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('bid_type', models.CharField(blank=True, default='Fixed Bid', max_length=100, null=True)),
                ('mailing_address', models.TextField()),
                ('mailing_city', models.CharField(max_length=50)),
                ('mailing_state', models.CharField(max_length=50)),
                ('mailing_postal_code', models.CharField(max_length=15)),
                ('mailing_country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag_list', models.CharField(blank=True, max_length=150, null=True)),
                ('pipeline', models.CharField(blank=True, max_length=150, null=True)),
                ('visibility', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.company')),
                ('record_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_owner', to=settings.AUTH_USER_MODEL)),
                ('user_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ManyToManyField(to='deals.pipelinestage')),
            ],
        ),
    ]
