# Generated by Django 5.0.2 on 2024-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='organization_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
