# Generated by Django 5.0.2 on 2024-06-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
