# Generated by Django 5.0.2 on 2024-04-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='organization_id',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
