# Generated by Django 5.0.2 on 2024-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_user_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='guest',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
