# Generated by Django 5.0.2 on 2024-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='deal_or_lead',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
