# Generated by Django 5.0.2 on 2024-06-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_deal_or_lead_alter_activity_notes_and_more'),
        ('contacts', '0007_alter_contact_organization_id_alter_contact_phone'),
        ('deals', '0002_deal_organization_id'),
        ('leads', '0002_rename_organization_lead_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='guest',
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_guest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='deal_guest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='deals.deal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='lead_guest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
            preserve_default=False,
        ),
    ]
