# Generated by Django 5.0.2 on 2024-06-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_activity_guest_activity_contact_guest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='deal_or_lead',
            new_name='guest_type',
        ),
    ]
