# Generated by Django 5.0.2 on 2024-06-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_contact_guest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
