# Generated by Django 5.0.2 on 2024-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_contact_guest_and_more'),
        ('contacts', '0007_alter_contact_organization_id_alter_contact_phone'),
        ('deals', '0003_alter_deal_organization_id'),
        ('leads', '0004_alter_lead_email_opted_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_purpose',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='contact_guest',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='deal_guest',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lead_guest',
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_guest',
            field=models.ManyToManyField(to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='deal_guest',
            field=models.ManyToManyField(to='deals.deal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead_guest',
            field=models.ManyToManyField(to='leads.lead'),
        ),
    ]
