# Generated by Django 5.0.2 on 2024-06-05 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0009_delete_activity'),
        ('contacts', '0007_alter_contact_organization_id_alter_contact_phone'),
        ('deals', '0003_alter_deal_organization_id'),
        ('leads', '0004_alter_lead_email_opted_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=150)),
                ('starting_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_date', models.DateField()),
                ('ending_time', models.TimeField()),
                ('availability', models.CharField(blank=True, default='Busy', max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('guest_type', models.CharField(blank=True, max_length=150, null=True)),
                ('host', models.CharField(max_length=250)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('deal_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
                ('lead_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('user_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
