# Generated by Django 5.0.2 on 2024-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_location_activity_purpose_activity_title'),
        ('contacts', '0007_alter_contact_organization_id_alter_contact_phone'),
        ('deals', '0003_alter_deal_organization_id'),
        ('leads', '0004_alter_lead_email_opted_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact_guests',
            field=models.ManyToManyField(related_name='contact_guests', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='deal_guests',
            field=models.ManyToManyField(related_name='deal_guests', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead_guests',
            field=models.ManyToManyField(related_name='lead_guests', to='leads.lead'),
        ),
    ]
