# Generated by Django 5.0.2 on 2024-06-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_activity_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='organization',
        ),
    ]
