# Generated by Django 5.0.2 on 2024-06-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_remove_activity_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizaton_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
