# Generated by Django 5.0.2 on 2024-06-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_activity_closed_activity_organizaton_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='organizaton_id',
            new_name='organization_id',
        ),
    ]
