# Generated by Django 5.0.2 on 2024-04-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('type_of_organization', models.CharField(max_length=150)),
                ('no_of_users', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('payment', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
