# Generated by Django 5.0.2 on 2024-04-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0002_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_logo/'),
        ),
    ]
