# Generated by Django 5.0.2 on 2024-04-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0004_alter_customer_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
