# Generated by Django 5.0.2 on 2024-04-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0005_alter_customer_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='payment',
            new_name='amount',
        ),
    ]
