# Generated by Django 5.0.2 on 2024-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0006_rename_payment_customer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
