# Generated by Django 5.0.2 on 2024-04-28 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0007_alter_customer_email_alter_customer_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
