# Generated by Django 5.0.2 on 2024-04-28 12:53

import crm_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0008_customer_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='organization_id',
            field=models.UUIDField(default=crm_admin.models.generate_organization_id, unique=True),
        ),
    ]
