# Generated by Django 5.0.2 on 2024-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0010_alter_customer_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
