# Generated by Django 5.0.2 on 2024-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0011_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='customer_favicon/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
