# Generated by Django 5.0.2 on 2024-05-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0012_customer_favicon_customer_website_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='expiry_date',
        ),
    ]
