# Generated by Django 5.0.2 on 2024-05-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0018_alter_plan_duration_alter_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
